version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-Jenkins
    container_name: jenkins-demo
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
    driver: local